name: projekti-2-ml-2024-vmnmte-mkdocs

services:
  mkdocs:
    container_name: vmnmte-container
    build:
      context: .
      dockerfile: docs.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs
    working_dir: /docs
    command: ["serve", "--dev-addr=0.0.0.0:8000", "--watch=docs"]
