image: python:3.10  # Käytetään Pythonin Docker-kuvaa

stages:
  - deploy

deploy-pages:
  stage: deploy
  script:
    - pip install mkdocs mkdocs-material  # Asennetaan MkDocs ja materiaaliteemat
    - mkdocs build  --site-dir public # Rakennetaan dokumentaatio
  pages: true
  artifacts:
    paths:
      - public  # GitLab Pages käyttää tätä kansiota julkaisua varten
  tags:
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "lisayksia"'  # Ajetaan vain, kun muutoksia pusketaan lisayksia-haaraan