version: '3.8'

services:
  ingestion:
    build:
      context: .
      dockerfile: ./ingestion/Dockerfile
    container_name: ingestion_container
    env_file:
      - ./shared/.env                       # Load environment variables from shared/.env file
    volumes:
      - ./ingestion/data:/data              # Mount data directory for CSV files
    depends_on:
      - database                            # Ensures CosmosDB is up before ingestion
    networks:
      - project-network

  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: database_container
    env_file:
      - ./shared/.env                       # Load environment variables from shared/.env file
    networks:
      - project-network
    ports:
      - "8081:8081"                         # Optional: expose port if CosmosDB emulator is used locally
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: app_container
    env_file:
      - ./shared/.env                       # Load environment variables from shared/.env file
    ports:
      - "${STREAMLIT_SERVER_PORT}:8501"     # Expose port for Streamlit app access
    depends_on:
      - database                            # Ensures database service is up before app
    networks:
      - project-network

networks:
  project-network:
    driver: bridge                          # Enable inter-service communication
