[server]
runOnSave = true

[theme]
primaryColor="#005EB8"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5F9FC"
textColor="#002F6C"
font="sans serif"

[theme.button]
backgroundColor="#005EB8"
textColor="#FFFFFF"